import React from 'react'
import { ScrollNav } from '../components/ScrollNav'

export const Project = () => (
    <section id="Project">
        <div className="container h-100">
            <div className="row h-90">
                <div className="col align-self-center">
                    <h2>Projects</h2>
                    <p>
                        This is a party comedy with a focus on responsibility and the need for faith. The story is about a confused bandit who is engaged to a necromancer. It starts aboard a space station used for in a dimensional warp. The story begins with someone discovering a report about themselves, climaxes with someone making a life-changing decision, and ends with someone being slandered.
                    </p>
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt vero veniam assumenda nesciunt, incidunt quod distinctio quaerat beatae repellendus eius consequuntur recusandae harum tempora eligendi porro molestiae impedit sunt cumque, quia ipsum suscipit mollitia aliquid voluptatum alias! Nulla maiores tenetur error, sunt eos laudantium sit voluptatum atque cumque numquam earum molestiae debitis magnam corrupti, esse est officiis nostrum. Sequi quasi in recusandae debitis, ipsa officia et molestiae temporibus iusto, amet, nam nisi at porro facilis alias quod id modi. Asperiores labore velit fugiat quidem eius tempora. Temporibus, nemo magni labore aperiam eveniet reprehenderit voluptas? Aliquid, unde odio fuga itaque iste nostrum quidem commodi quis quas eos nihil aperiam quae mollitia modi impedit obcaecati molestias aut similique repellat dolorum quos qui magni? Quisquam ipsam ad labore tenetur! Recusandae quas similique eaque voluptatibus fugit excepturi officia facere id iste natus reiciendis quis dolorum atque nihil, ratione dignissimos velit aliquid, consectetur alias sequi perspiciatis blanditiis. Nesciunt saepe reprehenderit fugit maiores modi veritatis quia, facere voluptatum, quidem delectus laborum rem molestiae quos autem dicta, enim possimus quae debitis provident. Cupiditate facere illum omnis dolores officia? Dolor maiores provident aut cum molestias consequatur quam, sint quae, voluptatem dolores, unde placeat laboriosam animi? Atque, iste maxime.</p>
                    <p>Eum laborum iusto saepe cupiditate ea culpa totam vitae autem doloremque enim tenetur facilis corrupti maxime nemo quisquam odit facere quidem, quis asperiores sapiente vel dolores? Soluta optio quam deleniti incidunt iusto! Fugiat, beatae, sed maiores praesentium voluptatum in cumque debitis dolorem fuga doloremque earum! Obcaecati, iusto. Corporis possimus similique placeat aliquid eaque, explicabo officiis facere enim rem! Tempore dolorum laudantium aperiam quisquam cum quae maiores quidem aspernatur cumque similique porro, et magnam cupiditate, repudiandae facilis ad corporis nesciunt alias obcaecati officiis fuga ipsam voluptatum. Totam iure cumque dolor cum voluptate odit id quibusdam dicta laborum nihil et maiores officia, sint tempora rem doloremque ipsum doloribus sunt architecto quasi deleniti facere. Nihil iste enim velit aliquid temporibus vitae modi fuga veniam tenetur laborum nostrum rem expedita doloremque accusantium, est deserunt. Excepturi molestiae consequuntur pariatur possimus ducimus nemo debitis. Consequatur esse provident ex alias unde debitis culpa enim nostrum sequi voluptatem veniam quo aut quia atque, maiores est suscipit asperiores. Natus veritatis ut consequuntur eaque eum. Laborum, aut provident dolores voluptates esse accusantium magni quis ipsa incidunt quisquam nemo impedit eius aspernatur omnis rem in voluptas quo iure? Rerum, dolor necessitatibus, beatae earum impedit reprehenderit delectus, fuga numquam fugiat odio in.</p>
                </div>
            </div>
            <ScrollNav to={'Resume'} />
        </div>
    </section>
)